### ISSUE TITLE
stock kernel build problem for G9 plus

### ISSUE THREAD

**Issue by deheshjou** [sm6150-motorola/android_kernel_motorola_sm6150#2]
Hi
I can build your released kernel source easily through clang or gcc but I can not build the stock kernel neither by clang nor gcc (aosp or my host ubuntu or gcc-linaro versions) and I face with different types of errors consecutively (related to compiler version or configuration and code syntax)!
The main question and ambiguity for me is that if it is possible for a company to release a source code, erroneous and buggy or it can be built with a special compiler config or version or under a specific condition?!

**Comment by Hasaber8** [comment]
Seems like you are doing something wrong, we are able to compile Moto G9+'s (odessa) stock kernel without any issue. From what I can understand from you message it seems like you are trying to compile the kernel without adding the kernel-modules, which Motorola ships separately.

Also there is readme for compiling Odessa kernel here:- https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPA30.19-Q3-32-39-1.txt

This branch here https://github.com/sm6150-motorola/android_kernel_motorola_sm6150/tree/staging/lineage-18.1 is using Odessa stock kernel released by Motorola

**Comment by deheshjou** [comment]
> Seems like you are doing something wrong, we are able to compile Moto G9+'s (odessa) stock kernel without any issue. From what I can understand from you message it seems like you are trying to compile the kernel without adding the kernel-modules, which Motorola ships separately.
> 
> Also there is readme for compiling Odessa kernel here:- https://github.com/MotorolaMobilityLLC/readme/blob/master/MMI-QPA30.19-Q3-32-39-1.txt
> 
> This branch here https://github.com/sm6150-motorola/android_kernel_motorola_sm6150/tree/staging/lineage-18.1 is using Odessa stock kernel released by Motorola

thanks for your help
